{{- /*gotype:go.flow.arcalot.io/pluginsdk/codegen.templateScope*/ -}}
{{- $externalReferences := .ExternalReferences -}}
{{- $pluginSchema := .PluginSchema -}}
{{- $packageName := .PackageName -}}
{{- import "go.flow.arcalot.io/pluginsdk/plugin" -}}
// Code generated by go generate; DO NOT EDIT.

package {{ .PackageName }}
{{ $generatedCode := partial "code/schema" .PluginSchema -}}
{{ $generatedSchema := partial "schema/schema" .PluginSchema -}}
{{- range $package := .ExternalReferences.Packages -}}
{{ import $package -}}
{{- end -}}
{{- with getImports }}
import ({{ range $import := . }}
    "{{ $import }}"
{{- end }}
)
{{- end }}

{{ $generatedCode }}

var pluginSchema = {{$generatedSchema}}
{{ if eq $packageName "main" }}
func main() {
    plugin.Run(pluginSchema)
}
{{- else }}
func Main() {
    plugin.Run(pluginSchema)
}
{{- end }}
