name: Build
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
jobs:
  lint_and_test:
    name: lint and test
    uses: arcalot/arcaflow-reusable-workflows/.github/workflows/go_lint_and_test.yaml@main
    with:
      go_version: ${{ vars.ARCALOT_GO_VERSION }}
  generate:
    name: go generate
    uses: arcalot/arcaflow-reusable-workflows/.github/workflows/go_generate.yaml@main
    with:
      go_version: ${{ vars.ARCALOT_GO_VERSION }}
